### ISSUE TITLE
Load unpacked no longer works

### ISSUE THREAD

**Issue by Savage-Indeed** [UoVE/Google-Forms-Unlocked#1]
Load unpacked no longer workson chrome://extensions, school prevented it so you can't open files in load unpacked on the chromebook 😢

**Comment by HackrTP** [comment]
I used Sh1mmer to have full control of my chromebook, I personally haven’t gotten yelled at or caught after unenrolling my chromebook but it is very risky. Follow their instructions very carefully and read everything before doing it, like reading the text at the bottom of their website on how to re enroll, I would take any precautions they suggest before doing it to your chromebook!
